services:
    nginx:
        image: nginx:latest
        ports:
            - "8090:80"
        volumes:
            - .:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        build:
          context: .
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        env_file:
            - .env
    mysql:
        image: mysql:9.1
        ports:
            - "3307:3306"
        env_file:
            - .env.mysql