services:
    nginx:
        image: nginx:1.27
        ports:
            - "8081:80"
        volumes:
            - .:/app
            - .nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        ports:
            - "9000:9000"
        volumes:
            - .:/code
        depends_on:
            - mysql
    mysql:
        image: mysql:9.1
        ports:
            - "3307:3306"
        env_file:
            - .env.mysql